name: getx_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # UTILITIES
  device_info: ^2.0.2
  package_info: ^2.0.2
  url_launcher: ^6.0.9
  win32: ^2.2.5
  intl: ^0.17.0

  # GETX STATE MANAGEMENT
  get: ^4.3.0
  get_storage: ^2.0.3

  # DATABASE
  sembast: ^3.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gif/loading_spinner.gif
    - assets/json/provinsi.json
    - assets/json/kabupaten.json
    - assets/json/kecamatan.json
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: QuicksandMedium
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
